### ISSUE TITLE
Can I get a compiled version for Windows?

### ISSUE THREAD

**Issue by ZILtoid1991** [buggins/dlangide#163]
Due to the recent upgrade of Xamarin to 6.0, I now cannot develop in D, tried to use Eclipse + DDT but it doesn't work.

**Comment by keywan-ghadami-oxid** [comment]
Hi @ZILtoid1991 i am a dlang user and for linux i use dub, so that should also work in windows so did you try that?:
- install dmd for windows https://dlang.org/dmd-windows.html#installation
- install Dub for windows: https://code.dlang.org/files/dub-1.0.0-setup.exe
- clone dlangide and run dub see "Building foreign projects" within https://code.dlang.org/getting_started
I only use dlangide but to be fair there are also other alternatives see
https://wiki.dlang.org/IDEs 
As far as remember @buggins and other users are able to compile on windows (i have only linux installed here) maybe they can provide binaries. Use also gitter https://gitter.im/buggins/dlangide to connect with them. There are also the dlang forum and the d irc channels where you can exchange with other users.
Hope you enjoy dlangide
best regards keywan

**Comment by buggins** [comment]
Fresh precompiled binaries usually can be found here: https://github.com/buggins/dlangide/releases
Includes mago-mi debugger.

**Comment by buggins** [comment]
to build and run, you install dmd and dub, then use

`dub run dlangide`

**Comment by buggins** [comment]
Closing
