### ISSUE TITLE
DCD Integration

### ISSUE THREAD

**Issue by SergeyOrlovXIM** [buggins/dlangide#203]
Probably it is not the issue but some Windows "feature". After 2-3 min DCD failes to work.
At starting DlangIDE all works fine: autocompletion, intellisense.
What wrong with TCP? Also is there the way to attach DCD client to DlangIDE?

**Comment by SergeyOrlovXIM** [comment]
Some detail goes here. DCD works till first start debug application

**Comment by buggins** [comment]
DCD is integrated into DlangIDE as a library. Just works in separate thread

**Comment by buggins** [comment]
> Some detail goes here. DCD works till first start debug application
Interesting finding. I saw DCD issue, but did not notice it's related to debugging.

**Comment by buggins** [comment]
Reproduced interesting behavior: 

- Start DlangIDE, open some project.
- Try Go To Definition on some external symbols (e.g. Thread.sleep, string) and internal (e.g. some function or var).
- Everything seems working (first invocation is delayed - until all files are parsed).
- Start debugging.
- Try Go To Definition on some external symbols (e.g. Thread.sleep, string) and internal (e.g. some function or var).
- Result: local functions are located successfully, but external are not.
-

**Comment by buggins** [comment]
Tried to destroy and recreate DCD ModuleCache before each DCD invocation. Doesn't help. DCD stops working after dub invocation.

**Comment by buggins** [comment]
I've created DCD issue 407.

DCD works ok until some thread is created (e.g. to invoke DUB for building).
After this operation DCD stops working correctly and can locate symbols only from current source file.

Root cause:
If some another thread is created after DCD thread instantiated ModuleCache, DCD is not able to process goToDefinition for symbol and other functions if they are related to other modules than current source file.
Probably, it's related to ModuleCache and/or allocators.

Steps to reproduce:
After creation of ModuleCache, start some thread and wait until it's finished.

**Comment by buggins** [comment]
Problem is localized, fix is prepared. Issue and PR is created for DSymbol project.

https://github.com/dlang-community/dsymbol/issues/32
