### ISSUE TITLE
Debugger support

### ISSUE THREAD

**Issue by buggins** [buggins/dlangide#7]

**Comment by keywan-ghadami** [comment]
If i switch the threads in selectbox i get a segfault, i am still trying to find the reason and fixing that.
 i would prefere to have the number (1,2,3) and the name of the thread in the selectbox(ok?), and maybe greyout the gc thread if we can identify it.
Sometimes on debugging the threads are still switching automaticly and stepping through the code is impossible. 
I will focus on this first because it blocks from doing other stuff.

**Comment by buggins** [comment]
Reproduced this crash.
BTW, there is Gitter chat https://gitter.im/buggins/dlangide?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by buggins** [comment]
Are you using FreeNode #D IRC channel?

**Comment by buggins** [comment]
Problem with Thread selection is fixed

**Comment by buggins** [comment]
(issue #94)

**Comment by arietto** [comment]
I suppose this enhancement has been implemented, so you can close this issue.
